### ISSUE TITLE
Textarea dans le courage et understanding

### ISSUE THREAD

**Issue by Steph4104** [Steph4104/kdm_2.0#30]
Est-ce que la section textarea après les checkbox de courage est pour l'information concernant la définition de ce qu'on a eu? (Ex: Matchmaker: Fait intamacy)?

![image](https://cloud.githubusercontent.com/assets/15112568/24586873/f58ccce2-1778-11e7-84c0-8e5be0f2ff62.png)

**Comment by Maelfrith** [comment]
Oui. Si tu choisi Stalwart, la definition de ce qu'est stalwart apparais dans cette section.

**Comment by Maelfrith** [comment]
Meme chose pour understanding.

**Comment by Steph4104** [comment]
Okay, j'aurais besoin du texte exacte pour chaques.

**Comment by Steph4104** [comment]
Bold - Courage:

(Showdown Phase) Stalwart: Ignore being knocked down by brain trauma and intimidation actions.
(Hunt Phase) Prepared: When rolling to determine a straggler, add your hunt experience to your roll result.
(Settlement Phase) Matchmaker: When you are a returning survivor, once per year you may spend (endeavor - logo d'étoile blanche dans le cercle noir) to (logo livre) intimacy.

Insight - Understanding:

(Showdown Phase) Analyse: At the start of the Survivors' turn, if you are adjacent to the monster, reveal the top AI card, then place it back on top of the deck.
(Hunt Phase) Explore: When you roll on an <strong>investigate</strong> table, add +2 to your roll result.
(Settlement Phase) Tinker: When you are a returning survivor, gain +1 (endeavor - logo d'étoile blanche dans le cercle noir) to use this settlement phase.
